"""New initial commit.

Revision ID: 2d9dfd60b3a1
Revises: 
Create Date: 2024-09-16 00:57:40.791068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9dfd60b3a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biomes'))
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions'))
    )
    op.create_table('habitats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_habitats_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habitats')),
    sa.UniqueConstraint('name', name=op.f('uq_habitats_name'))
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('biome_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['biome_id'], ['biomes.id'], name=op.f('fk_trainers_biome_id_biomes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainers')),
    sa.UniqueConstraint('name', name=op.f('uq_trainers_name'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('danger', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('habitat_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('length(content) >= 50', name=op.f('ck_reviews_')),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitats.id'], name=op.f('fk_reviews_habitat_id_habitats')),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_reviews_trainer_id_trainers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_table('sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('blurb', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('habitat_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitats.id'], name=op.f('fk_sightings_habitat_id_habitats')),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_sightings_trainer_id_trainers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sightings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sightings')
    op.drop_table('reviews')
    op.drop_table('trainers')
    op.drop_table('habitats')
    op.drop_table('regions')
    op.drop_table('biomes')
    # ### end Alembic commands ###
