"""Add image columns to various tables.

Revision ID: 5d54380764c9
Revises: 60b3de49f561
Create Date: 2024-09-08 02:18:54.558227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d54380764c9'
down_revision = '60b3de49f561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habitats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))

    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('image')

    with op.batch_alter_table('habitats', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
