"""Move danger column from habitat to habitat review.

Revision ID: 60b3de49f561
Revises: cf2281a61621
Create Date: 2024-09-06 16:11:33.721914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b3de49f561'
down_revision = 'cf2281a61621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habitats', schema=None) as batch_op:
        batch_op.drop_column('danger')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('danger', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('danger')

    with op.batch_alter_table('habitats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('danger', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
