"""Add region table and relationship to habitat.

Revision ID: 8523e1f37471
Revises: dec10b100600
Create Date: 2024-08-29 12:36:01.597547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8523e1f37471'
down_revision = 'dec10b100600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions'))
    )
    with op.batch_alter_table('habitats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_habitats_region_id_regions'), 'regions', ['region_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habitats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_habitats_region_id_regions'), type_='foreignkey')
        batch_op.drop_column('region_id')

    op.drop_table('regions')
    # ### end Alembic commands ###
