"""Add foreign keys to reviews table.

Revision ID: 86c88c9d42c1
Revises: 674540a83f43
Create Date: 2024-08-26 13:27:46.607284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c88c9d42c1'
down_revision = '674540a83f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habitats', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_habitats_name'), ['name'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habitat_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('traier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_habitat_id_habitats'), 'habitats', ['habitat_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_traier_id_trainers'), 'trainers', ['traier_id'], ['id'])

    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_trainers_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_trainers_name'), type_='unique')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_traier_id_trainers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_habitat_id_habitats'), type_='foreignkey')
        batch_op.drop_column('traier_id')
        batch_op.drop_column('habitat_id')

    with op.batch_alter_table('habitats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_habitats_name'), type_='unique')

    # ### end Alembic commands ###
