"""Add rare sighting table and relationships.

Revision ID: cf2281a61621
Revises: 8fc23881a809
Create Date: 2024-08-30 14:22:51.025063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2281a61621'
down_revision = '8fc23881a809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('blurb', sa.String(), nullable=False),
    sa.Column('habitat_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitats.id'], name=op.f('fk_sightings_habitat_id_habitats')),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_sightings_trainer_id_trainers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sightings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sightings')
    # ### end Alembic commands ###
