"""New initial migration.

Revision ID: dec10b100600
Revises: 
Create Date: 2024-08-28 15:31:38.809386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec10b100600'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('danger', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habitats')),
    sa.UniqueConstraint('name', name=op.f('uq_habitats_name'))
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainers')),
    sa.UniqueConstraint('name', name=op.f('uq_trainers_name'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('habitat_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('length(content) >= 50', name=op.f('ck_reviews_')),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitats.id'], name=op.f('fk_reviews_habitat_id_habitats')),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_reviews_trainer_id_trainers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('trainers')
    op.drop_table('habitats')
    # ### end Alembic commands ###
